### ISSUE TITLE
ICCV 2023 paper: PoseDiffusion: Solving Pose Estimation via Diffusion-aided Bundle Adjustment

### ISSUE THREAD

**Issue by jytime** [amusi/ICCV2023-Papers-with-Code#52]
Paper name/title: PoseDiffusion: Solving Pose Estimation via Diffusion-aided Bundle Adjustment
Paper link: https://arxiv.org/pdf/2306.15667.pdf
Code link: https://github.com/facebookresearch/PoseDiffusion

Topic: Diffusion model / Structure from Motion (SfM)
Personally I think SfM is a more appropriate field for this paper though I did not find it in the readme file :)

Thanks for maintaining such a repository.

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
