### ISSUE TITLE
ICCV 2023 paper: "MARS: Model-agnostic Biased Object Removal without Additional Supervision for Weakly-Supervised Semantic Segmentation"

### ISSUE THREAD

**Issue by shjo-april** [amusi/ICCV2023-Papers-with-Code#53]
Paper name/title: "MARS: Model-agnostic Biased Object Removal without Additional Supervision for Weakly-Supervised Semantic Segmentation"
Paper link: https://arxiv.org/abs/2304.09913
Code link: https://github.com/shjo-april/MARS

Thank you for organizing ICCV papers!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
