### ISSUE TITLE
Add ICCV 2023 Paper

### ISSUE THREAD

**Issue by ldkong1205** [amusi/ICCV2023-Papers-with-Code#54]
Thanks for maintaining this repository!

We would like to recommend our accepted paper at ICCV 2023:

- **Title:** Robo3D: Towards Robust and Reliable 3D Perception against Corruptions
- **arXiv link:** https://arxiv.org/abs/2303.17597
- **Project Page:** https://ldkong.com/Robo3D
- **GitHub link:** https://github.com/ldkong1205/Robo3D
- **Related areas:** `point cloud`, `autonomous driving`, `robustness`

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
