### ISSUE TITLE
Add ICCV 2023 Paper

### ISSUE THREAD

**Issue by ldkong1205** [amusi/ICCV2023-Papers-with-Code#55]
Thanks for maintaining this repository!

We would like to recommend our accepted paper at ICCV 2023:

- **Title:** Rethinking Range View Representation for LiDAR Segmentation
- **arXiv link:** https://arxiv.org/abs/2303.05367
- **Project Page:** https://ldkong.com/RangeFormer
- **Related areas:** `3d semantic segmentation`, `autonomous driving`, `vision transformer`

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
