### ISSUE TITLE
Add ICCV 2023 paper FateZero: Fusing Attentions for Zero-shot Text-based Video Editing

### ISSUE THREAD

**Issue by ChenyangQiQi** [amusi/ICCV2023-Papers-with-Code#56]
Thanks for maintaining this repository!

Paper name: FateZero: Fusing Attentions for Zero-shot Text-based Video Editing
Paper link: https://arxiv.org/abs/2303.09535
Project link: https://fate-zero-edit.github.io/
Code link: https://github.com/ChenyangQiQi/FateZero
Related areas: video editing; image editing; style transfer; text-driven editing;

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
