### ISSUE TITLE
Add ICCV 2023 paper: Learning Human Motion Representations: A Unified Perspective

### ISSUE THREAD

**Issue by Walter0807** [amusi/ICCV2023-Papers-with-Code#61]
Thanks for maintaining this project!
Paper name/title: MotionBERT: A Unified Perspective on Learning Human Motion Representations
Homepage: https://motionbert.github.io/ 
Paper: https://arxiv.org/abs/2210.06551
Code: https://github.com/Walter0807/MotionBERT

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
