### ISSUE TITLE
Please add paper: Cross-modal Orthogonal High-rank Augmentation for RGB-Event Transformer-trackers

### ISSUE THREAD

**Issue by ZHU-Zhiyu** [amusi/ICCV2023-Papers-with-Code#63]
Paper name: Cross-modal Orthogonal High-rank Augmentation for RGB-Event Transformer-trackers
Paper link: https://arxiv.org/abs/2307.04129
Code link: https://github.com/ZHU-Zhiyu/High-Rank_RGB-Event_Tracker
Related areas: Object Tracking

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
