### ISSUE TITLE
[Please add ICCV 2023 paper] Group DETR: Fast DETR Training with Group-Wise One-to-Many Assignment

### ISSUE THREAD

**Issue by charlesCXK** [amusi/ICCV2023-Papers-with-Code#64]
Thanks for maintaining this repository!

Paper name: Group DETR: Fast DETR Training with Group-Wise One-to-Many Assignment
Paper link: https://arxiv.org/pdf/2207.13085.pdf
Code link: https://github.com/Atten4Vis/GroupDETR
Related areas: Object Detection

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
