### ISSUE TITLE
add paper AvatarCraft: Transforming Text into Neural Human Avatars with Parameterized Shape and Pose Control

### ISSUE THREAD

**Issue by songrise** [amusi/ICCV2023-Papers-with-Code#66]
Title: AvatarCraft: Transforming Text into Neural Human Avatars with Parameterized Shape and Pose Control
Code: https://github.com/songrise/AvatarCraft
paper: https://arxiv.org/abs/2303.17606
website: https://arxiv.org/abs/2303.17606
Area: avatars/diffusion/nerf

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
