### ISSUE TITLE
New ICCV'23 paper: BeLFusion: Latent Diffusion for Behavior-Driven Human Motion Prediction

### ISSUE THREAD

**Issue by BarqueroGerman** [amusi/ICCV2023-Papers-with-Code#67]
Hi, great job keeping track of the ICCV'23 papers, thank you! Could you please add ours?

**Paper name**: BeLFusion: Latent Diffusion for Behavior-Driven Human Motion Prediction
**Paper link**: https://arxiv.org/abs/2211.14304
**Code link**: https://github.com/BarqueroGerman/BeLFusion
**Related areas**: 3D Human Motion Generation + Diffusion

Thank you for your time!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
