### ISSUE TITLE
Add ICCV 2023 paper: Zero-Shot Composed Image Retrieval with Textual Inversion

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [amusi/ICCV2023-Papers-with-Code#68]
Thanks for this very useful repository!

Paper name: Zero-Shot Composed Image Retrieval with Textual Inversion
Paper link: https://arxiv.org/abs/2303.15247
Code link: https://github.com/miccunifi/SEARLE
Related areas: Vision-Language

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
