### ISSUE TITLE
Add ICCV 2023 paper: Multimodal Garment Designer: Human-Centric Latent Diffusion Models for Fashion Image Editing

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [amusi/ICCV2023-Papers-with-Code#69]
Thanks again for this awesome repository!

Paper name: Multimodal Garment Designer: Human-Centric Latent Diffusion Models for Fashion Image Editing
Paper link: https://arxiv.org/abs/2304.02051
Code link: https://github.com/aimagelab/multimodal-garment-designer
Related areas: Image Generation

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
