### ISSUE TITLE
Add ICCV 2023 paper: DDFM: Denoising Diffusion Model for Multi-Modality Image Fusion.

### ISSUE THREAD

**Issue by Zhaozixiang1228** [amusi/ICCV2023-Papers-with-Code#70]
Thanks for maintaining this repository!

Paper name: DDFM: Denoising Diffusion Model for Multi-Modality Image Fusion.
Paper link: https://arxiv.org/abs/2303.06840
Code link: https://github.com/Zhaozixiang1228/MMIF-DDFM
Related areas: Low-level Vision; Diffusion Models; Image Fusion

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
