### ISSUE TITLE
Add ICCV 2023 paper: Spherical Space Feature Decomposition for Guided Depth Map Super-Resolution. 

### ISSUE THREAD

**Issue by Zhaozixiang1228** [amusi/ICCV2023-Papers-with-Code#71]
Thanks for maintaining this repository!

Paper name: Spherical Space Feature Decomposition for Guided Depth Map Super-Resolution.
Paper link: https://arxiv.org/abs/2303.08942
Code link: https://github.com/Zhaozixiang1228/GDSR-SSDNet
Related areas: Low-level Vision; Image Super-Resolution

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
