### ISSUE TITLE
Add ICCV 2023 paper: DIRE for Diffusion-Generated Image Detection.

### ISSUE THREAD

**Issue by ZhendongWang6** [amusi/ICCV2023-Papers-with-Code#72]
Paper title: DIRE for Diffusion-Generated Image Detection
Paper link: [https://arxiv.org/abs/2303.09295](https://arxiv.org/abs/2303.09295)
Code link: [https://github.com/ZhendongWang6/DIRE](https://github.com/ZhendongWang6/DIRE)
keywords: Diffusion forensics, Generated image detection

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
