### ISSUE TITLE
Add ICCV2023 paper: Revisiting Domain-Adaptive 3D Object Detection by Reliable, Diverse and Class-balanced Pseudo-Labeling

### ISSUE THREAD

**Issue by zhuoxiao-chen** [amusi/ICCV2023-Papers-with-Code#74]
Related Area: 3D Object Detection, Domain Adaptation
Paper title: Revisiting Domain-Adaptive 3D Object Detection by Reliable, Diverse and Class-balanced Pseudo-Labeling
Paper link: https://arxiv.org/abs/2307.07944
Code link: https://github.com/zhuoxiao-chen/ReDB-DA-3Ddet
Thank you very much!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
