### ISSUE TITLE
Add ICCV2023 paper: Instance-aware Dynamic Prompt Tuning for Pre-trained Point Cloud Models

### ISSUE THREAD

**Issue by gimpong** [amusi/ICCV2023-Papers-with-Code#75]
Related Area: 3D点云(3D Point Cloud)
Paper title: Instance-aware Dynamic Prompt Tuning for Pre-trained Point Cloud Models
Paper link: https://arxiv.org/abs/2304.07221
Code link: https://github.com/zyh16143998882/ICCV23-IDPT
Thank you very much!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
