### ISSUE TITLE
Add ICCV2023 paper: EigenTrajectory: Low-Rank Descriptors for Multi-Modal Trajectory Forecasting

### ISSUE THREAD

**Issue by InhwanBae** [amusi/ICCV2023-Papers-with-Code#76]
Thanks for this very useful repository!

**Paper name**: EigenTrajectory: Low-Rank Descriptors for Multi-Modal Trajectory Forecasting
**Homepage**: [https://inhwanbae.github.io/publication/eigentrajectory/](https://inhwanbae.github.io/publication/eigentrajectory/)
**Paper link**: [https://arxiv.org/abs/2307.09306](https://arxiv.org/abs/2307.09306)
**Code link:** [https://github.com/InhwanBae/EigenTrajectory](https://github.com/InhwanBae/EigenTrajectory)
**Related areas**: 轨迹预测(Trajectory Prediction)

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
