### ISSUE TITLE
Add ICCV2023 paper: BoxDiff: Text-to-Image Synthesis with Training-Free Box-Constrained Diffusion

### ISSUE THREAD

**Issue by Sierkinhane** [amusi/ICCV2023-Papers-with-Code#77]
Related areas: Diffusion Models(扩散模型)
Paper name/title: BoxDiff: Text-to-Image Synthesis with Training-Free Box-Constrained Diffusion
Paper link: https://arxiv.org/abs/2307.10816
Code link: https://github.com/Sierkinhane/BoxDiff
keywords: text-to-image synthesis, diffusion models, layout-to-image synthesis

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
