### ISSUE TITLE
Add Paper Name: Exploring Video Quality Assessment on User Generated Contents from Aesthetic and Technical Perspectives

### ISSUE THREAD

**Issue by teowu** [amusi/ICCV2023-Papers-with-Code#78]
Paper Name: Exploring Video Quality Assessment on User Generated Contents from Aesthetic and Technical Perspectives
Authors: Haoning Wu, Erli Zhang, Liang Liao, Chaofeng Chen, Jingwen Hou, Annan Wang, Wenxiu Sun, Qiong Yan, Weisi Lin
Arxiv Link: arxiv.org/abs/2211.04894v3
Github Code and Repo: https://github.com/VQAssessment/DOVER

Thank you!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
