### ISSUE TITLE
Add ICCV2023 paper: Self-supervised Character-to-Character Distillation for Text Recognition

### ISSUE THREAD

**Issue by TongkunGuan** [amusi/ICCV2023-Papers-with-Code#79]
title: Self-supervised Character-to-Character Distillation for Text Recognition
paper: https://arxiv.org/pdf/2211.00288.pdf
code: https://github.com/TongkunGuan/CCD
keywords: text recognition

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
