### ISSUE TITLE
Add ICCV2023 paper: Integrally Migrating Pre-trained Transformer Encoder-decoders for Visual Object Detection

### ISSUE THREAD

**Issue by LiewFeng** [amusi/ICCV2023-Papers-with-Code#80]
title: Integrally Migrating Pre-trained Transformer Encoder-decoders for Visual Object Detection
paper: https://arxiv.org/abs/2205.09613
code: https://github.com/LiewFeng/imTED
keywords: object detection
blog in chinese: https://zhuanlan.zhihu.com/p/645282546
Thanks a lot!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
