### ISSUE TITLE
Add ICCV2023 paper: SA-BEV: Generating Semantic-Aware Bird's-Eye-View Feature for Multi-view 3D Object Detection

### ISSUE THREAD

**Issue by mengtan00** [amusi/ICCV2023-Papers-with-Code#81]
title: SA-BEV: Generating Semantic-Aware Bird's-Eye-View Feature for Multi-view 3D Object Detection
paper: https://arxiv.org/abs/2307.11477
code: https://github.com/mengtan00/SA-BEV
keywords: 3d object detection
Thanks a lot!

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
