### ISSUE TITLE
Add ICCV2023 paper: MRN: Multiplexed Routing Network for Incremental Multilingual Text Recognition

### ISSUE THREAD

**Issue by simplify23** [amusi/ICCV2023-Papers-with-Code#82]
Related areas: OCR
Paper name/title: MRN: Multiplexed Routing Network for Incremental Multilingual Text Recognition
Paper link: https://arxiv.org/abs/2305.14758
Code link: https://github.com/simplify23/MRN
Blog in Chinese: https://zhuanlan.zhihu.com/p/643948935
keywords: OCR, Incremental learning

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
