### ISSUE TITLE
ADD ICCV 2023 Paper: FlipNeRF: Flipped Reflection Rays for Few-shot Novel View Synthesis

### ISSUE THREAD

**Issue by shawn615** [amusi/ICCV2023-Papers-with-Code#83]
Thanks for maintaining this useful repository :)

Paper name: FlipNeRF: Flipped Reflection Rays for Few-shot Novel View Synthesis
Project Page: https://shawn615.github.io/flipnerf/
Code link: https://github.com/shawn615/FlipNeRF
Paper link: https://arxiv.org/abs/2306.17723
Related areas: NeRF

**Comment by amusi** [comment]
Now the project has been added, thanks for sharing.
